### ISSUE TITLE
I HAVE NO IDEA WTF IM DOING PLS HELP!!

### ISSUE THREAD

**Issue by max666999** [zeenode/selfbot#14]
pls i have no idea wtf im doing-- i just want to set up the damn bot but your shit isn't very clear on how- plus on ur webpage the discord link don't work

**Comment by owersite** [comment]
It is not a bot, it is a selfbot maybe that is what you have not took in mind, and its not shit, it has very clear instructions as well.
And Discord link does not work since there is no more discord support for it.
