### ISSUE TITLE
Replit

### ISSUE THREAD

**Issue by shkeffy** [zeenode/selfbot#17]
Hello, @owersite, @Bekston, @flowitoo, @v01d2, deep apologies for the pings, I was just wondering if any of you know how to make it work on Replit? If so, contact me on Discord at Shkeffy#9999, and thank you so very much for taking the time to actually read this, most developers don't :/

**Comment by Classifyzzz** [comment]
it doesnt work on replit

**Comment by shkeffy** [comment]
😭
