### ISSUE TITLE
Some help

### ISSUE THREAD

**Issue by Sunlightcoder** [zeenode/selfbot#18]
Can someone help me figure out how to using this make a self bot for copy messages from one server to another? I'm a new to discord.py and python itself, ad will try to do it myself this day. Thx for attention)

**Comment by PhilippPR** [comment]
I don't really understand what u want.

If u want a bot that can copy a message in a specific channel to another channel on another guild, u could use something like this:
```
@bot.event
async def on_message(message):

    FROMCHANNEL = id_here
    TOCHANNEL = id_here

    if message.channel.id == FROMCHANNEL:
        chnl1 = bot.get_channel(TOCHANNEL)
        await chnl1.send(message.content)
        await message.channel.send("> Message sent to "+chnl1.mention)

**Comment by owersite** [comment]
Thank you Philipp for response, anyway, as Philipp said.
