### ISSUE TITLE
serverinfo not fully working

### ISSUE THREAD

**Issue by VerstreuteSeele** [zeenode/selfbot#5]
as it seems like this is the first non-troll issue xD

well, your serverinfo command has two bugs:

1. it always says "1 Member"
2. it says "Owner: None"

any quick fix for this?

**Comment by VerstreuteSeele** [comment]
Also.. im getting an error saying " sh: 1: mode: not found "

**Comment by owersite** [comment]
hey VerstreuteSeele i'd be happy to help you with your issue, i gotta admit it was really a long time for a respond but now we will update the code and you should see if everything is as it should be now, thanks for reporting the issue! Much love,
owersite

**Comment by owersite** [comment]
Fixed, if u find any other issues open an issue, thanks !
